import { SHARD_IDS } from "./shard-ids";

export const MAIN_WEB_SHARD_IDS = [
  SHARD_IDS.SETTINGS,
  SHARD_IDS.WINDOW_EFFECT,
  SHARD_IDS.I18N,
  SHARD_IDS.UPDATER,
  SHARD_IDS.SHELL,
  SHARD_IDS.STATIC_CACHE,
  SHARD_IDS.TRAY,
  SHARD_IDS.MINI,
  SHARD_IDS.HISTORY,
  SHARD_IDS.REPLAY,
  SHARD_IDS.ONGOING_GAME,
  SHARD_IDS.AUTOMATION,
  SHARD_IDS.TOOLS,
] as const;

export const MINI_WEB_SHARD_IDS = [
  SHARD_IDS.SETTINGS,
  SHARD_IDS.WINDOW_EFFECT,
  SHARD_IDS.I18N,
  SHARD_IDS.STATIC_CACHE,
  SHARD_IDS.MINI,
  SHARD_IDS.ONGOING_GAME,
] as const;

export const MINI_ONGOING_GAME_SHARD_LABEL = "MiniOngoingGameShard";
