// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CherryAugment = {
  id: number;
  nameTRA: string;
  augmentSmallIconPath: string;
  rarity: string;
};
