// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClaimToolActivityEntryDto = {
  timestampMs: number;
  level: ClaimToolActivityLevel;
  category: ClaimToolCategory | null;
  action: string;
  message: string;
};

export type ClaimToolActivityLevel = "info" | "warning" | "error";

export type ClaimToolCategory = "reward" | "mission" | "eventHub";

export type ClaimToolClaimRequestDto = {
  rewards: Array<string>;
  missions: Array<string>;
  eventHub: Array<string>;
};

export type ClaimToolClaimablesDto = {
  rewards: Array<ClaimToolItemDto>;
  missions: Array<ClaimToolItemDto>;
  eventHub: Array<ClaimToolItemDto>;
  refreshedAtMs: number;
};

export type ClaimToolItemDto = {
  id: string;
  category: ClaimToolCategory;
  title: string;
  subtitle: string | null;
  iconUrl: string | null;
  quantity: number | null;
  choiceCount: number;
  status: ClaimToolItemStatus;
  reason: string | null;
  children: Array<ClaimToolRewardPreviewDto>;
};

export type ClaimToolItemStatus = "claimable" | "skipped";

export type ClaimToolRewardPreviewDto = {
  id: string;
  title: string;
  subtitle: string | null;
  iconUrl: string | null;
  quantity: number | null;
};

export type ClaimToolRunResultDto = {
  snapshot: ClaimToolSnapshotDto;
  claimed: number;
  skipped: number;
  failed: number;
};

export type ClaimToolSnapshotDto = {
  autoClaimEnabled: boolean;
  isRunning: boolean;
  lastRunAtMs: number | null;
  lastError: string | null;
  recentActivity: Array<ClaimToolActivityEntryDto>;
};
