// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SummonerInfo } from "./summoner";

export type LcuInstanceInfo = {
  pid: number;
  port: number;
  state: LcuInstanceState;
  isFocused: boolean;
  installDir: string | null;
  region: string | null;
  summoner: SummonerInfo | null;
};

export type LcuInstanceState = "ready" | "authenticating" | "closing";
