// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LcuMapProperties, MapSpellRule } from "./maps";

export type EventType = "Update" | "Create" | "Delete";

export type GameClient = {
  observerServerIp: string;
  observerServerPort: number;
  running: boolean;
  serverIp: string;
  serverPort: number;
  visible: boolean;
};

export type GameData = {
  gameId: number;
  gameName: string;
  isCustomGame: boolean;
  password: string;
  playerChampionSelections: Array<PlayerChampionSelection>;
  queue: Queue;
  spectatorKey: string;
  spectatorsAllowed: boolean;
  teamOne: Array<Team>;
  teamTwo: Array<Team>;
};

export type GameDodge = {
  dodgeIds: Array<number>;
  phase: string;
  state: string;
};

export type GameTypeConfig = {
  advancedLearningQuests: boolean;
  allowTrades: boolean;
  banMode: string;
  banTimeDuration: number;
  battleBoost: boolean;
  crossTeamChampionPool: boolean;
  deathMatch: boolean;
  doNotRemove: boolean;
  duplicatedPick: boolean;
  exclusivePick: boolean;
  id: number;
  learningQuests: boolean;
  mainPickTimerDuration: number;
  maxAllowableBans: number;
  name: string;
  onboardCoopBeginner: boolean;
  pickMode: string;
  postPickTimerDuration: number;
  reroll: boolean;
  teamChampionPool: boolean;
};

export type GameflowSessionData = {
  gameClient: GameClient;
  gameData: GameData;
  gameDodge: GameDodge;
  map: Map;
  phase: string;
};

export type Map = {
  assets: Record<string, unknown>;
  categorizeContentBundles: Record<string, unknown>;
  description: string;
  gameMode: string;
  gameModeName: string;
  gameModeShortName: string;
  gameMutator: string;
  id: number;
  isRgm: boolean;
  mapStringId: string;
  name: string;
  perPositionDisallowedSummonerSpells: { [key in string]: MapSpellRule };
  perPositionRequiredSummonerSpells: { [key in string]: MapSpellRule };
  platformId: string;
  platformName: string;
  properties: LcuMapProperties;
};

export type PlayerChampionSelection = {
  championId: number;
  puuid: string;
  selectedSkinIndex: number;
  spell1Id: number;
  spell2Id: number;
};

export type Queue = {
  allowablePremadeSizes: Array<number>;
  areFreeChampionsAllowed: boolean;
  assetMutator: string;
  category: string;
  championsRequiredToPlay: number;
  description: string;
  detailedDescription: string;
  gameMode: string;
  gameTypeConfig: GameTypeConfig;
  id: number;
  isBotHonoringAllowed: boolean;
  isCustom: boolean;
  isRanked: boolean;
  isTeamBuilderManaged: boolean;
  lastToggleOffTime: number;
  lastToggleOnTime: number;
  mapId: number;
  maximumParticipantListSize: number;
  minLevel: number;
  minimumParticipantListSize: number;
  name: string;
  numPlayerPerTeam: number;
  queueAvailability: string;
  queueRewards: QueueRewards;
  removalFromGameAllowed: boolean;
  removalFromGameDelayMinutes: number;
  shortName: string;
  showPositionSelector: boolean;
  spectatorEnabled: boolean;
  type: string;
};

export type QueueRewards = {
  isChampionPointsEnabled: boolean;
  isIpEnabled: boolean;
  isXpEnabled: boolean;
  partySizeIpRewards: Array<Record<string, unknown>>;
};

export type Team = {
  championId: number;
  lastSelectedSkinIndex: number;
  profileIconId: number;
  puuid: string;
  selectedPosition: string;
  selectedRole: string;
  summonerId: number;
  summonerInternalName: string;
  summonerName: string;
  teamOwner: boolean;
  teamParticipantId: number;
};

export type TeamMember = {
  assignedPosition: string | null;
  cellId: number;
  championId: number;
  championPickIntent: number;
  gameName: string;
  internalName: string;
  isAutoFilled: boolean;
  isHumanoid: boolean;
  nameVisibilityType: string;
  obfuscatePuuid: string;
  obfuscateSummonerId: number;
  pickMode: number;
  pickTurn: number;
  playerAlias: string;
  playerType: string;
  puuid: string;
  selectedSkinId: number;
  spell1Id: number;
  spell2Id: number;
  summonerId: number;
  tagLine: string;
  team: number;
  wardSkinId: number;
};
