// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanePosition } from "./lane";
import type { LcuMapProperties, MapSpellRule } from "./maps";

export type Action = {
  actorCellId: number;
  championId: number;
  completed: boolean;
  duration: number;
  id: number;
  isAllyAction: boolean;
  isInProgress: boolean;
  pickTurn: number;
  type: string;
};

export type Bans = {
  myTeamBans: Array<Record<string, unknown>>;
  numBans: number;
  theirTeamBans: Array<Record<string, unknown>>;
};

export type ChampSelectSessionData = {
  actions: Array<Array<Action>>;
  allowBattleBoost: boolean;
  allowDuplicatedPicks: boolean;
  allowLockedEvents: boolean;
  allowPlayerPickSameChampion: boolean;
  allowRerolling: boolean;
  allowSkinSelection: boolean;
  allowSubsetChampionPicks: boolean;
  bans: Bans;
  benchChampions: Array<Record<string, unknown>>;
  benchEnabled: boolean;
  boostableSkinCount: number;
  chatDetails: ChatDetails;
  counter: number;
  disallowBanningTeammateHoveredChampions: boolean;
  gameId: number;
  hasSimultaneousBans: boolean;
  hasSimultaneousPicks: boolean;
  id: string;
  isCustomGame: boolean;
  isLegacyChampSelect: boolean;
  isSpectating: boolean;
  localPlayerCellId: number;
  lockedEventIndex: number;
  myTeam: Array<TeamMember>;
  pickOrderSwaps: Array<Swap>;
  positionSwaps: Array<Swap>;
  queueId: number;
  rerollsRemaining: number;
  showQuitButton: boolean;
  skipChampionSelect: boolean;
  theirTeam: Array<TeamMember>;
  timer: Timer;
  trades: Array<Swap>;
};

/**
 * Response shape of `GET /lol-champ-select/v1/summoners/{cellId}`.
 *
 * The published LCU OpenAPI schema for `LolChampSelectChampSelectSummoner`
 * documents the UI-facing fields only (`actingBackgroundAnimationState`,
 * `championIconStyle`, …).  In practice the endpoint also returns the full
 * identity block used elsewhere in champ-select (puuid, summoner id, game
 * name, tag line, name visibility …).  This matters because
 * `/lol-champ-select/v1/session` obfuscates puuid / summoner id for ranked
 * pre-reveal games, but the per-cell endpoint still returns the real values
 * — that is exactly what we need to seed the ongoing-game roster on cold
 * start.
 *
 * Every field is `#[serde(default)]` so that shape drift on the LCU side
 * cannot break deserialization.
 */
export type ChampSelectSummoner = {
  puuid: string;
  summonerId: number;
  gameName: string;
  tagLine: string;
  internalName: string;
  nameVisibilityType: NameVisibilityType;
  obfuscatedPuuid: string;
  obfuscatedSummonerId: number;
  cellId: number;
  slotId: number;
  team: number;
  assignedPosition: string;
  championId: number;
  championPickIntent: number;
  selectedSkinId: number;
  skinId: number;
  spell1Id: number;
  spell2Id: number;
  wardSkinId: number;
  isSelf: boolean;
  isOnPlayersTeam: boolean;
  isPlaceholder: boolean;
  isActingNow: boolean;
  isDonePicking: boolean;
  isPickIntenting: boolean;
  areSummonerActionsComplete: boolean;
  actingBackgroundAnimationState: string;
  activeActionType: string;
  banIntentSquarePortraitPath: string;
  championIconStyle: string;
  championName: string;
  currentChampionVotePercentInteger: number;
  entitledFeatureType: string;
  pickSnipedClass: string;
  shouldShowActingBar: boolean;
  shouldShowBanIntentIcon: boolean;
  shouldShowExpanded: boolean;
  shouldShowRingAnimations: boolean;
  shouldShowSelectedSkin: boolean;
  shouldShowSpells: boolean;
  showMuted: boolean;
  showTrades: boolean;
  skinSplashPath: string;
  spell1IconPath: string;
  spell2IconPath: string;
  statusMessageKey: string;
  tradeId: number;
};

export type ChatDetails = {
  mucJwtDto: MucJwtDto;
  multiUserChatId: string;
  multiUserChatPassword: string;
};

export type EventType = "Update" | "Create" | "Delete";

export type GameClient = {
  observerServerIp: string;
  observerServerPort: number;
  running: boolean;
  serverIp: string;
  serverPort: number;
  visible: boolean;
};

export type GameData = {
  gameId: number;
  gameName: string;
  isCustomGame: boolean;
  password: string;
  playerChampionSelections: Array<PlayerChampionSelection>;
  queue: Queue;
  spectatorKey: string;
  spectatorsAllowed: boolean;
  teamOne: Array<Team>;
  teamTwo: Array<Team>;
};

export type GameDodge = {
  dodgeIds: Array<number>;
  phase: string;
  state: string;
};

export type GameTypeConfig = {
  advancedLearningQuests: boolean;
  allowTrades: boolean;
  banMode: string;
  banTimeDuration: number;
  battleBoost: boolean;
  crossTeamChampionPool: boolean;
  deathMatch: boolean;
  doNotRemove: boolean;
  duplicatedPick: boolean;
  exclusivePick: boolean;
  id: number;
  learningQuests: boolean;
  mainPickTimerDuration: number;
  maxAllowableBans: number;
  name: string;
  onboardCoopBeginner: boolean;
  pickMode: string;
  postPickTimerDuration: number;
  reroll: boolean;
  teamChampionPool: boolean;
};

export type GameflowSessionData = {
  gameClient: GameClient;
  gameData: GameData;
  gameDodge: GameDodge;
  map: Map;
  phase: Phase;
};

export type Map = {
  assets: Record<string, unknown>;
  categorizeContentBundles: Record<string, unknown>;
  description: string;
  gameMode: string;
  gameModeName: string;
  gameModeShortName: string;
  gameMutator: string;
  id: number;
  isRgm: boolean;
  mapStringId: string;
  name: string;
  perPositionDisallowedSummonerSpells: { [key in string]: MapSpellRule };
  perPositionRequiredSummonerSpells: { [key in string]: MapSpellRule };
  platformId: string;
  platformName: string;
  properties: LcuMapProperties;
};

export type MucJwtDto = {
  channelClaim: string;
  domain: string;
  jwt: string;
  targetRegion: string;
};

export type NameVisibilityType = "HIDDEN" | "VISIBLE";

export type Phase =
  | "None"
  | "ChampSelect"
  | "Matchmaking"
  | "GameStart"
  | "ReadyCheck"
  | "InProgress"
  | "WaitingForStats"
  | "TerminatedInError"
  | "Lobby"
  | "EndOfGame"
  | "InGame"
  | "Unknown";

export type PlayerChampionSelection = {
  championId: number;
  puuid: string;
  selectedSkinIndex: number;
  spell1Id: number;
  spell2Id: number;
};

export type Queue = {
  allowablePremadeSizes: Array<number>;
  areFreeChampionsAllowed: boolean;
  assetMutator: string;
  category: string;
  championsRequiredToPlay: number;
  description: string;
  detailedDescription: string;
  gameMode: string;
  gameTypeConfig: GameTypeConfig;
  id: number;
  isBotHonoringAllowed: boolean;
  isCustom: boolean;
  isRanked: boolean;
  isTeamBuilderManaged: boolean;
  lastToggleOffTime: number;
  lastToggleOnTime: number;
  mapId: number;
  maximumParticipantListSize: number;
  minLevel: number;
  minimumParticipantListSize: number;
  name: string;
  numPlayerPerTeam: number;
  queueAvailability: string;
  queueRewards: QueueRewards;
  removalFromGameAllowed: boolean;
  removalFromGameDelayMinutes: number;
  shortName: string;
  showPositionSelector: boolean;
  spectatorEnabled: boolean;
  type: string;
};

export type QueueRewards = {
  isChampionPointsEnabled: boolean;
  isIpEnabled: boolean;
  isXpEnabled: boolean;
  partySizeIpRewards: Array<Record<string, unknown>>;
};

export type Swap = { cellId: number; id: number; state: string };

export type Team = {
  championId: number;
  lastSelectedSkinIndex: number;
  profileIconId: number;
  puuid: string;
  selectedPosition: LanePosition;
  selectedRole: string;
  summonerId: number;
  summonerInternalName: string;
  summonerName: string;
  teamOwner: boolean;
  teamParticipantId: number;
};

export type TeamMember = {
  assignedPosition: LanePosition;
  cellId: number;
  championId: number;
  championPickIntent: number;
  gameName: string;
  internalName: string;
  isAutoFilled: boolean;
  isHumanoid: boolean;
  nameVisibilityType: NameVisibilityType;
  obfuscatePuuid: string;
  obfuscateSummonerId: number;
  pickMode: number;
  pickTurn: number;
  playerAlias: string;
  playerType: string;
  puuid: string;
  selectedSkinId: number;
  spell1Id: number;
  spell2Id: number;
  summonerId: number;
  tagLine: string;
  team: number;
  wardSkinId: number;
};

export type Timer = {
  adjustTimeLeftInPhase: number;
  internalNowEpocMs: number;
  isInfinite: boolean;
  phase: string;
  totalTimeInPhase: number;
};
