// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LcuChatFriend = { availability: string, displayGroupId: number, displayGroupName: string, gameName: string, gameTag: string, groupId: number, groupName: string, icon: number, id: string, isP2PConversationMuted: boolean, lastSeenOnlineTimestamp: string | null, lol: LcuChatLolState, name: string, note: string, patchline: string, pid: string, platformId: string, product: string, productName: string, puuid: string, statusMessage: string, summary: string, summonerId: number, time: number, };

export type LcuChatFriendGroup = { collapsed: boolean, id: number, isLocalized: boolean, isMetaGroup: boolean, name: string, priority: number, };

export type LcuChatLolState = { bannerIdSelected: string, challengeCrystalLevel: string, challengePoints: string, challengeTitleSelected: string, challengeTokensSelected: string, championId: string, companionId: string, damageSkinId: string, gameId: string, gameMode: string, gameQueueType: string, gameStatus: string, iconOverride: string, initRankStat: string, initSummoner: string, isObservable: string, mapId: string, mapSkinId: string, profileIcon: string, pty: string, queueId: string, regalia: string, skinVariant: string, skinname: string, timeStamp: string, };
