// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LcuMapProperties = { suppressRunesMasteriesPerks: boolean };

export type MapSpellRule = { spells: Array<number> };
