// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MatchDetail = {
  gameId: number;
  gameDuration: number;
  gameMode: string;
  gameCreation: number;
  queueId: number;
  participants: Array<Participant>;
};

export type MatchOutcome = "victory" | "defeat" | "remake" | "terminated";

export type MatchSummary = {
  gameId: number;
  championId: number;
  win: boolean;
  outcome: MatchOutcome;
  teamId: number;
  kills: number;
  deaths: number;
  assists: number;
  cs: number;
  totalDamageDealtToChampions: number;
  damageShare: number;
  spell1Id: number;
  spell2Id: number;
  perkPrimaryRuneId: number;
  perkSubStyleId: number;
  items: [number, number, number, number, number, number, number];
  mapId: number;
  gameDuration: number;
  gameMode: string;
  gameCreation: number;
  queueId: number;
  participants: Array<MatchSummaryParticipant>;
};

export type MatchSummaryParticipant = {
  puuid: string;
  championId: number;
  gameName: string;
  tagLine: string;
  teamId: number;
};

export type Participant = {
  puuid: string;
  championId: number;
  summonerName: string;
  gameName: string;
  tagLine: string;
  teamId: number;
  kills: number;
  deaths: number;
  assists: number;
  totalDamageDealtToChampions: number;
  totalDamageTaken: number;
  goldEarned: number;
  visionScore: number;
  cs: number;
  items: [number, number, number, number, number, number, number];
  spell1Id: number;
  spell2Id: number;
  perkPrimaryStyle: number;
  perkSubStyle: number;
  win: boolean;
};
