// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpCallRecordDto = { id: string, toolName: string, clientName: string, clientVersion: string, sessionId: string | null, calledAt: number, protocol: string, transport: string, };

export type McpClientDto = { sessionId: string, clientName: string, clientVersion: string, connectedAt: number, lastSeenAt: number, };

export type McpServerStateDto = { running: boolean, endpoint: string | null, clients: Array<McpClientDto>, callRecords: Array<McpCallRecordDto>, };

export type McpToolDto = { name: string, title: string | null, description: string | null, readOnlyHint: boolean | null, destructiveHint: boolean | null, idempotentHint: boolean | null, openWorldHint: boolean | null, };
