// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackendNotificationLevelDto = "info" | "warning" | "error";

export type BackendNotificationRequestDto = { source: string, level: BackendNotificationLevelDto, titleKey: string, bodyKey: string | null, values: { [key: string]: string | number | boolean }, dedupeKey: string | null, system: BackendNotificationSystemModeDto, };

export type BackendNotificationSystemModeDto = "off" | "respectUserSetting" | "force";
