// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {
  ChampSelectSessionData,
  GameflowSessionData,
  TeamMember,
} from "./lcu_events";

export type OngoingGameMatchHistoryFilter = "CurrentMode" | "All";

export type OngoingGamePhase = "Idle" | "ChampSelect" | "InGame";

export type OngoingGameUpdated = {
  phase: OngoingGamePhase;
  match_history_filter: OngoingGameMatchHistoryFilter;
  gameflow_session: GameflowSessionData | null;
  champ_select_session: ChampSelectSessionData | null;
  team_members: Array<TeamMember>;
};
