// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RawMatchSummariesResponse } from "./matches";
import type { RankStats } from "./rank";
import type { SummonerInfo } from "./summoner";

export type OngoingGamePhase = "Idle" | "ChampSelect" | "InGame";

export type OngoingGamePhaseChanged = {
  phase: OngoingGamePhase;
  loading: boolean;
  our_side: Side | null;
  blue_players: Array<PlayerSlot>;
  red_players: Array<PlayerSlot>;
};

export type OngoingGamePlayerSnapshot = {
  puuid: string;
  side: Side;
  champion_id: number | null;
  summoner: SummonerInfo;
  ranked: RankStats | null;
  match_history: RawMatchSummariesResponse | null;
  champion_mastery: Record<string, unknown> | null;
};

export type OngoingGameSnapshotUpdated = {
  phase: OngoingGamePhase;
  loading: boolean;
  our_side: Side | null;
  blue_players: Array<OngoingGamePlayerSnapshot>;
  red_players: Array<OngoingGamePlayerSnapshot>;
};

export type PlayerSlot = {
  puuid: string;
  champion_id: number | null;
  side: Side;
};

export type PremadeGroup = {
  group_id: string;
  members: Array<string>;
  side: Side;
};

export type Side = "Blue" | "Red";
