// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameflowSessionData, TeamMember } from "./lcu_events";

export type OngoingGameContextInfo = {
  queue_id: number | null;
  queue_name: string | null;
  queue_short_name: string | null;
  map_id: number | null;
  map_name: string | null;
  game_mode: string | null;
  game_mode_name: string | null;
  game_mode_short_name: string | null;
  match_history_filter: OngoingGameMatchHistoryFilter;
  match_history_tag: string | null;
};

export type OngoingGameMatchHistoryFilter = "CurrentMode" | "All";

export type OngoingGamePhase = "Idle" | "ChampSelect" | "InGame";

export type OngoingGameUpdated = {
  phase: OngoingGamePhase;
  loading: boolean;
  context: OngoingGameContextInfo;
  gameflow_session: GameflowSessionData | null;
  team_members: Array<TeamMember>;
};
