// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LcuReplayConfiguration = {
  gameVersion: string;
  isInTournament: boolean;
  isLoggedIn: boolean;
  isPatching: boolean;
  isPlayingGame: boolean;
  isPlayingReplay: boolean;
  isReplaysEnabled: boolean;
  isReplaysForEndOfGameEnabled: boolean;
  isReplaysForMatchHistoryEnabled: boolean;
  minServerVersion: string;
  minutesUntilReplayConsideredLost: number;
};

export type LcuReplayDownloadState =
  | "checking"
  | "found"
  | "download"
  | "downloading"
  | "watch"
  | "incompatible"
  | "unknown";

export type LcuReplayMetadata = {
  downloadProgress: number;
  gameId: number;
  state: LcuReplayDownloadState;
};

export type ReplayClient = {
  pid: number;
  label: string;
  family: ReplayClientFamily;
  serverId: string | null;
  gameVersion: string | null;
  installDir: string | null;
  isFocused: boolean;
  available: boolean;
  reason: string | null;
};

export type ReplayClientFamily = "TENCENT" | "RIOT";

export type ReplayLaunchMethod = "lcu" | "localExecutable";

export type ReplayEntry = {
  id: string;
  path: string;
  fileName: string;
  platformId: string | null;
  family: ReplayClientFamily | null;
  gameId: number | null;
  championIds: Array<number>;
  championAliases: Array<string>;
  patchVersion: string | null;
  metadataError: string | null;
  gameLengthMs: number | null;
  lastGameChunkId: number | null;
  lastKeyFrameId: number | null;
  fileSizeBytes: number;
  createdAtMs: number | null;
  modifiedAtMs: number | null;
  launchAvailability: ReplayLaunchAvailability;
};

export type ReplayFolder = {
  path: string;
  enabled: boolean;
  exists: boolean;
  sources: Array<ReplayFolderSource>;
};

export type ReplayFolderSource = {
  kind: ReplayFolderSourceKind;
  clientPid: number | null;
  clientFamily: ReplayClientFamily | null;
  clientServerId: string | null;
};

export type ReplayFolderSourceKind = "user" | "client" | "default";

export type ReplayLaunchAvailability = {
  canLaunch: boolean;
  reason: string | null;
  launchMethod: ReplayLaunchMethod | null;
  clientPid: number | null;
  clientFamily: ReplayClientFamily | null;
  clientServerId: string | null;
  clientGameVersion: string | null;
};

export type ReplayLibrarySnapshot = {
  folders: Array<ReplayFolder>;
  clients: Array<ReplayClient>;
  entries: Array<ReplayEntry>;
};

export type ReplayMatchContext = {
  gameId: number;
  gameVersion: string | null;
  gameType: string | null;
  queueId: number | null;
  gameEnd: number | null;
  platformId: string | null;
  sgpServerId: string | null;
};

export type ReplayMatchState = {
  metadata: LcuReplayMetadata;
  configuration: LcuReplayConfiguration | null;
};
