// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LcuReplayConfiguration = {
  gameVersion: string;
  isInTournament: boolean;
  isLoggedIn: boolean;
  isPatching: boolean;
  isPlayingGame: boolean;
  isPlayingReplay: boolean;
  isReplaysEnabled: boolean;
  isReplaysForEndOfGameEnabled: boolean;
  isReplaysForMatchHistoryEnabled: boolean;
  minServerVersion: string;
  minutesUntilReplayConsideredLost: number;
};

export type LcuReplayDownloadState =
  | "checking"
  | "found"
  | "download"
  | "downloading"
  | "watch"
  | "incompatible"
  | "unknown";

export type LcuReplayMetadata = {
  downloadProgress: number;
  gameId: number;
  state: LcuReplayDownloadState;
};

export type ReplayEntry = {
  id: string;
  path: string;
  fileName: string;
  platformId: string | null;
  gameId: number | null;
  patchVersion: string | null;
  metadataError: string | null;
  gameLengthMs: number | null;
  lastGameChunkId: number | null;
  lastKeyFrameId: number | null;
  fileSizeBytes: number;
  createdAtMs: number | null;
  modifiedAtMs: number | null;
  launchAvailability: ReplayLaunchAvailability;
};

export type ReplayExecutable = {
  path: string;
  label: string;
  gameBaseDir: string | null;
  gameVersion: string | null;
  exists: boolean;
};

export type ReplayFolder = { path: string; enabled: boolean; exists: boolean };

export type ReplayLaunchAvailability = {
  canLaunch: boolean;
  reason: string | null;
  executablePath: string | null;
};

export type ReplayLibrarySnapshot = {
  folders: Array<ReplayFolder>;
  executables: Array<ReplayExecutable>;
  entries: Array<ReplayEntry>;
};

export type ReplayMatchContext = {
  gameId: number;
  gameVersion: string | null;
  gameType: string | null;
  queueId: number | null;
  gameEnd: number | null;
  platformId: string | null;
  sgpServerId: string | null;
};

export type ReplayMatchState = {
  metadata: LcuReplayMetadata;
  configuration: LcuReplayConfiguration | null;
};
