// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SettingControlDto =
  | { kind: "select" }
  | { kind: "toggle" }
  | { kind: "text"; placeholder_key: string | null }
  | {
      kind: "number";
      placeholder_key: string | null;
      min: number | null;
      max: number | null;
      step: number | null;
    };

export type SettingDefinitionDto = {
  id: string;
  labelKey: string;
  scope: SettingScopeDto;
  control: SettingControlDto;
  defaultValue: unknown;
  order: number | null;
  visible: boolean | null;
  options: Array<SettingOptionDto> | null;
};

export type SettingOptionDto = { value: string; labelKey: string };

export type SettingScopeDto = "frontend" | "backend" | "shared";

export type SettingsBootstrapDto = {
  definitions: Array<SettingDefinitionDto>;
  snapshot: SettingsSnapshotDto;
};

export type SettingsChangedEventDto = {
  changes: { [key: string]: unknown };
  version: number;
  source: string | null;
};

export type SettingsPatchDto = {
  changes: { [key: string]: unknown };
  expectedVersion: number | null;
  source: string | null;
};

export type SettingsPatchResultDto = { snapshot: SettingsSnapshotDto };

export type SettingsSnapshotDto = {
  version: number;
  values: { [key: string]: unknown };
};
