// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SettingControlDto = { "kind": "select" } | { "kind": "toggle" } | { "kind": "text", placeholderKey: string | null, } | { "kind": "number", placeholderKey: string | null, min: number | null, max: number | null, step: number | null, } | { "kind": "action" };

export type SettingDefinitionDto = { id: string, labelKey: string, hintKey: string | null, scope: SettingScopeDto, control: SettingControlDto, defaultValue: unknown, order: number | null, visible: boolean | null, options: Array<SettingOptionDto> | null, };

export type SettingOptionDto = { value: string, labelKey: string, displayLabel: string | null, };

export type SettingScopeDto = "frontend" | "backend" | "shared";

export type SettingsBootstrapDto = { definitions: Array<SettingDefinitionDto>, snapshot: SettingsSnapshotDto, };

export type SettingsChangedEventDto = { changes: { [key: string]: unknown }, source: string | null, };

export type SettingsDefinitionsChangedEventDto = { ids: Array<string>, };

export type SettingsSnapshotDto = { values: { [key: string]: unknown }, };
