// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SgpServerEndpoints = { matchHistory: string | null, common: string | null, };

export type SgpServersConfig = { version: number, lastUpdate: number, from: string, servers: { [key in string]: SgpServerEndpoints }, tencentServerMatchHistoryInteroperability: Array<string>, tencentServerSpectatorInteroperability: Array<string>, tencentServerSummonerInteroperability: Array<string>, serverNames: { [key in string]: { [key in string]: string } }, };
