// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShardInfoDto = { id: string, label: string, status: ShardStatusDto, dependencies: Array<string>, setupDurationMs: number | null, };

export type ShardStatusDto = { "kind": "running" } | { "kind": "failed", error: string, } | { "kind": "skipped" };

export type ShardsSnapshotDto = { shards: Array<ShardInfoDto>, };
