// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShardStatusDto =
  | { kind: "running" }
  | { kind: "failed"; error: string }
  | { kind: "skipped" };

export interface ShardInfoDto {
  id: string;
  label: string;
  status: ShardStatusDto;
  dependencies: Array<string>;
  setupDurationMs: number | null;
}

export interface ShardsSnapshotDto {
  shards: Array<ShardInfoDto>;
}
