// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SummonerInfo = {
  puuid: string;
  gameName: string;
  tagLine: string;
  profileIconId: number;
  summonerLevel: number;
  level: number;
  privacy: string;
  accountId: number;
  id: number;
  summonerId: number;
  name: string;
  internalName: string;
  expPoints: number;
  expToNextLevel: number;
  levelAndXpVersion: number;
  lastGameDate: number;
  revisionDate: number;
  revisionId: number;
  nameChangeFlag: boolean;
  unnamed: boolean;
};

export type SummonerSearchResult = {
  puuid: string;
  gameName: string;
  tagLine: string;
  profileIconId: number;
  summonerLevel: number;
  sgpServerId: string;
  privacy: string;
};
