// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RankedQueueStats = {
  queueType: string;
  tier: string;
  division: string;
  leaguePoints: number;
  wins: number;
  losses: number;
};

export type RankedSummary = {
  solo: RankedQueueStats | null;
  flex: RankedQueueStats | null;
};

export type SummonerInfo = {
  puuid: string;
  gameName: string;
  tagLine: string;
  profileIconId: number;
  summonerLevel: number;
};
