import {
  createGlobalTheme,
  createGlobalThemeContract,
} from "@vanilla-extract/css";

export const vars = createGlobalThemeContract({
  color: {
    primary: "primary",
    success: "success",
    error: "error",
    background: "background",
    backgroundRaw: "backgroundRaw",
    popupBackgroud: "popup-backgroud",
    foreground: "foreground",
    accent: "accent",
    surface: "surface",
    accentForeground: "accent-foreground",
    mutedForeground: "muted-foreground",
    border: "border",
    popover: "popover",
    popoverBorder: "popover-border",
  },
  settings: {
    controlBg: "settings-control-bg",
    controlBorder: "settings-control-border",
    controlBorderRadius: "settings-control-border-radius",
    controlText: "settings-control-text",
    controlHoverBorder: "settings-control-hover-border",
    surfaceBorderRadius: "settings-surface-border-radius",
    selectMenuBg: "settings-select-menu-bg",
    selectMenuBorder: "settings-select-menu-border",
    selectMenuShadow: "settings-select-menu-shadow",
    selectChevron: "settings-select-chevron",
    selectOptionHoverBg: "settings-select-option-hover-bg",
    selectOptionSelectedBg: "settings-select-option-selected-bg",
    selectOptionSelectedText: "settings-select-option-selected-text",
    switchTrackOn: "settings-switch-track-on",
    switchTrackOff: "settings-switch-track-off",
    switchThumb: "settings-switch-thumb",
    switchText: "settings-switch-text",
  },
});

createGlobalTheme(":root", vars, {
  color: {
    primary: "oklch(0.72 0.19 62)",
    success: "oklch(0.73 0.18 142)",
    error: "oklch(0.65 0.25 27)",
    background: vars.color.backgroundRaw,
    backgroundRaw: "oklch(0.994 0 0)",
    popupBackgroud: `oklch(from ${vars.color.backgroundRaw} 0.972 c h)`,
    foreground: "oklch(0.3 0 0)",
    accent: `oklch(from ${vars.color.backgroundRaw} 0.86 c h)`,
    surface: `oklch(from ${vars.color.foreground} 0.24 c h / 0.22)`,
    accentForeground: `oklch(from ${vars.color.foreground} 0.2 c h)`,
    mutedForeground: `oklch(from ${vars.color.foreground} 0.55 c h)`,
    border: `oklch(from ${vars.color.accent} 0.88 c h)`,
    popover: `oklch(from ${vars.color.backgroundRaw} 0.98 c h)`,
    popoverBorder: vars.color.border,
  },
  settings: {
    controlBg: `oklch(from ${vars.color.backgroundRaw} 1 c h)`,
    controlBorder: vars.color.border,
    controlBorderRadius: "8px",
    controlText: vars.color.foreground,
    controlHoverBorder: `oklch(from ${vars.color.primary} l c h / 0.45)`,
    surfaceBorderRadius: "10px",
    selectMenuBg: vars.color.popover,
    selectMenuBorder: vars.color.popoverBorder,
    selectMenuShadow: `oklch(from ${vars.color.foreground} 0.25 c h / 0.2)`,
    selectChevron: vars.color.mutedForeground,
    selectOptionHoverBg: `oklch(from ${vars.color.accent} 0.9 c h)`,
    selectOptionSelectedBg: vars.color.accent,
    selectOptionSelectedText: vars.color.accentForeground,
    switchTrackOn: `oklch(from ${vars.color.primary} l c h / 0.3)`,
    switchTrackOff: vars.color.accent,
    switchThumb: vars.color.foreground,
    switchText: vars.color.mutedForeground,
  },
});

createGlobalTheme(":root.dark", vars, {
  color: {
    primary: "oklch(0.72 0.19 62)",
    success: "oklch(0.73 0.18 142)",
    error: "oklch(0.65 0.25 27)",
    background: `oklch(from ${vars.color.backgroundRaw} 0.16 0.015 270 / 0.22)`,
    backgroundRaw: "oklch(0.244 0 0)",
    popupBackgroud: `oklch(from ${vars.color.backgroundRaw} 0.22 0 0)`,
    foreground: "oklch(0.985 0 0)",
    accent: `oklch(from ${vars.color.backgroundRaw} 0.32 0.02 270 / 0.85)`,
    surface: `oklch(from ${vars.color.backgroundRaw} 0.223 0.002 17.273 / 0.34)`,
    accentForeground: vars.color.foreground,
    mutedForeground: `oklch(from ${vars.color.foreground} 0.708 c h)`,
    border: `oklch(from ${vars.color.backgroundRaw} 0.4 0.015 270 / 0.3)`,
    popover: `oklch(from ${vars.color.backgroundRaw} 0.2 0.015 270 / 0.98)`,
    popoverBorder: `oklch(from ${vars.color.foreground} l c h / 0.12)`,
  },
  settings: {
    controlBg: vars.color.background,
    controlBorder: vars.color.border,
    controlBorderRadius: "8px",
    controlText: vars.color.foreground,
    controlHoverBorder: `oklch(from ${vars.color.primary} l c h / 0.45)`,
    surfaceBorderRadius: "10px",
    selectMenuBg: vars.color.popover,
    selectMenuBorder: vars.color.popoverBorder,
    selectMenuShadow: `oklch(from ${vars.color.backgroundRaw} 0.06 c h / 0.6)`,
    selectChevron: vars.color.mutedForeground,
    selectOptionHoverBg: `oklch(from ${vars.color.accent} 0.36 c h / 0.45)`,
    selectOptionSelectedBg: vars.color.accent,
    selectOptionSelectedText: vars.color.accentForeground,
    switchTrackOn: `oklch(from ${vars.color.primary} l c h / 0.82)`,
    switchTrackOff: vars.color.accent,
    switchThumb: vars.color.foreground,
    switchText: vars.color.mutedForeground,
  },
});
