// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanePosition } from "./lane";
import type { LcuMapProperties, MapSpellRule } from "./maps";

export type Action = {
  actorCellId: bigint;
  championId: bigint;
  completed: boolean;
  duration: bigint;
  id: bigint;
  isAllyAction: boolean;
  isInProgress: boolean;
  pickTurn: bigint;
  type: string;
};

export type Bans = {
  myTeamBans: Array<Record<string, unknown>>;
  numBans: bigint;
  theirTeamBans: Array<Record<string, unknown>>;
};

export type ChampSelectSessionData = {
  actions: Array<Array<Action>>;
  allowBattleBoost: boolean;
  allowDuplicatedPicks: boolean;
  allowLockedEvents: boolean;
  allowPlayerPickSameChampion: boolean;
  allowRerolling: boolean;
  allowSkinSelection: boolean;
  allowSubsetChampionPicks: boolean;
  bans: Bans;
  benchChampions: Array<Record<string, unknown>>;
  benchEnabled: boolean;
  boostableSkinCount: bigint;
  chatDetails: ChatDetails;
  counter: bigint;
  disallowBanningTeammateHoveredChampions: boolean;
  gameId: bigint;
  hasSimultaneousBans: boolean;
  hasSimultaneousPicks: boolean;
  id: string;
  isCustomGame: boolean;
  isLegacyChampSelect: boolean;
  isSpectating: boolean;
  localPlayerCellId: bigint;
  lockedEventIndex: bigint;
  myTeam: Array<TeamMember>;
  pickOrderSwaps: Array<Swap>;
  positionSwaps: Array<Swap>;
  queueId: bigint;
  rerollsRemaining: bigint;
  showQuitButton: boolean;
  skipChampionSelect: boolean;
  theirTeam: Array<TeamMember>;
  timer: Timer;
  trades: Array<Swap>;
};

export type ChatDetails = {
  mucJwtDto: MucJwtDto;
  multiUserChatId: string;
  multiUserChatPassword: string;
};

export type EventType = "Update" | "Create" | "Delete";

export type GameClient = {
  observerServerIp: string;
  observerServerPort: number;
  running: boolean;
  serverIp: string;
  serverPort: number;
  visible: boolean;
};

export type GameData = {
  gameId: bigint;
  gameName: string;
  isCustomGame: boolean;
  password: string;
  playerChampionSelections: Array<PlayerChampionSelection>;
  queue: Queue;
  spectatorKey: string;
  spectatorsAllowed: boolean;
  teamOne: Array<Team>;
  teamTwo: Array<Team>;
};

export type GameDodge = {
  dodgeIds: Array<bigint>;
  phase: string;
  state: string;
};

export type GameTypeConfig = {
  advancedLearningQuests: boolean;
  allowTrades: boolean;
  banMode: string;
  banTimeDuration: bigint;
  battleBoost: boolean;
  crossTeamChampionPool: boolean;
  deathMatch: boolean;
  doNotRemove: boolean;
  duplicatedPick: boolean;
  exclusivePick: boolean;
  id: bigint;
  learningQuests: boolean;
  mainPickTimerDuration: bigint;
  maxAllowableBans: bigint;
  name: string;
  onboardCoopBeginner: boolean;
  pickMode: string;
  postPickTimerDuration: bigint;
  reroll: boolean;
  teamChampionPool: boolean;
};

export type GameflowSessionData = {
  gameClient: GameClient;
  gameData: GameData;
  gameDodge: GameDodge;
  map: Map;
  phase: Phase;
};

export type Map = {
  assets: Record<string, unknown>;
  categorizeContentBundles: Record<string, unknown>;
  description: string;
  gameMode: string;
  gameModeName: string;
  gameModeShortName: string;
  gameMutator: string;
  id: bigint;
  isRgm: boolean;
  mapStringId: string;
  name: string;
  perPositionDisallowedSummonerSpells: { [key in string]: MapSpellRule };
  perPositionRequiredSummonerSpells: { [key in string]: MapSpellRule };
  platformId: string;
  platformName: string;
  properties: LcuMapProperties;
};

export type MatchmakingDodgeData = { dodgerId: bigint; state: string };

export type MatchmakingLowPriorityData = {
  bustedLeaverAccessToken: string;
  penalizedSummonerIds: Array<bigint>;
  penaltyTime: number;
  penaltyTimeRemaining: number;
  reason: string;
};

export type MatchmakingReadyCheckData = {
  declinerIds: Array<bigint>;
  dodgeWarning: string;
  playerResponse: ReadyCheckPlayerResponse;
  state: ReadyCheckState;
  suppressUx: boolean;
  timer: number;
};

export type MatchmakingSearchData = {
  dodgeData: MatchmakingDodgeData;
  errors: Array<Record<string, unknown>>;
  estimatedQueueTime: number;
  isCurrentlyInQueue: boolean;
  lobbyId: string;
  lowPriorityData: MatchmakingLowPriorityData;
  queueId: bigint;
  readyCheck: MatchmakingReadyCheckData;
  searchState: MatchmakingSearchState;
  timeInQueue: number;
};

export type MatchmakingSearchState =
  | "Invalid"
  | "Searching"
  | "Found"
  | "Unknown";

export type MucJwtDto = {
  channelClaim: string;
  domain: string;
  jwt: string;
  targetRegion: string;
};

export type NameVisibilityType = "HIDDEN" | "VISIBLE";

export type Phase =
  | "None"
  | "ChampSelect"
  | "Matchmaking"
  | "GameStart"
  | "ReadyCheck"
  | "InProgress"
  | "WaitingForStats"
  | "TerminatedInError"
  | "Lobby"
  | "EndOfGame"
  | "InGame"
  | "Unknown";

export type PlayerChampionSelection = {
  championId: bigint;
  puuid: string;
  selectedSkinIndex: bigint;
  spell1Id: bigint;
  spell2Id: bigint;
};

export type Queue = {
  allowablePremadeSizes: Array<bigint>;
  areFreeChampionsAllowed: boolean;
  assetMutator: string;
  category: string;
  championsRequiredToPlay: bigint;
  description: string;
  detailedDescription: string;
  gameMode: string;
  gameTypeConfig: GameTypeConfig;
  id: bigint;
  isBotHonoringAllowed: boolean;
  isCustom: boolean;
  isRanked: boolean;
  isTeamBuilderManaged: boolean;
  lastToggleOffTime: bigint;
  lastToggleOnTime: bigint;
  mapId: bigint;
  maximumParticipantListSize: bigint;
  minLevel: bigint;
  minimumParticipantListSize: bigint;
  name: string;
  numPlayerPerTeam: bigint;
  queueAvailability: string;
  queueRewards: QueueRewards;
  removalFromGameAllowed: boolean;
  removalFromGameDelayMinutes: bigint;
  shortName: string;
  showPositionSelector: boolean;
  spectatorEnabled: boolean;
  type: string;
};

export type QueueRewards = {
  isChampionPointsEnabled: boolean;
  isIpEnabled: boolean;
  isXpEnabled: boolean;
  partySizeIpRewards: Array<Record<string, unknown>>;
};

export type ReadyCheckPlayerResponse =
  | "None"
  | "Accepted"
  | "Declined"
  | "Unknown";

export type ReadyCheckState =
  | "Invalid"
  | "InProgress"
  | "EveryoneReady"
  | "Unknown";

export type Swap = { cellId: bigint; id: bigint; state: string };

export type Team = {
  championId: bigint;
  lastSelectedSkinIndex: bigint;
  profileIconId: bigint;
  puuid: string;
  selectedPosition: LanePosition;
  selectedRole: string;
  summonerId: bigint;
  summonerInternalName: string;
  summonerName: string;
  teamOwner: boolean;
  teamParticipantId: bigint;
};

export type TeamMember = {
  assignedPosition: LanePosition;
  cellId: bigint;
  championId: bigint;
  championPickIntent: bigint;
  gameName: string;
  internalName: string;
  isAutoFilled: boolean;
  isHumanoid: boolean;
  nameVisibilityType: NameVisibilityType;
  obfuscatePuuid: string;
  obfuscateSummonerId: bigint;
  pickMode: bigint;
  pickTurn: bigint;
  playerAlias: string;
  playerType: string;
  puuid: string;
  selectedSkinId: bigint;
  spell1Id: bigint;
  spell2Id: bigint;
  summonerId: bigint;
  tagLine: string;
  team: bigint;
  wardSkinId: bigint;
};

export type Timer = {
  adjustTimeLeftInPhase: bigint;
  internalNowEpocMs: bigint;
  isInfinite: boolean;
  phase: string;
  totalTimeInPhase: bigint;
};
