// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LcuMap = {
  assets: { [key in string]: string };
  categorizedContentBundles: Record<string, unknown>;
  description: string;
  gameMode: string;
  gameModeDescription: string;
  gameModeName: string;
  gameModeShortName: string;
  gameMutator: string;
  id: bigint;
  isDefault: boolean;
  isRgm: boolean;
  locStrings: { [key in string]: string };
  mapStringId: string;
  name: string;
  perPositionDisallowedSummonerSpells: { [key in string]: LcuMapSpellRule };
  perPositionRequiredSummonerSpells: { [key in string]: LcuMapSpellRule };
  platformId: string;
  platformName: string;
  properties: LcuMapProperties;
  setModalButtonBottom: bigint;
  setModalButtonLeft: bigint;
  tftSetOverride: string;
  tutorialCards: Array<LcuMapTutorialCard>;
};

export type LcuMapProperties = { suppressRunesMasteriesPerks: boolean };

export type LcuMapSpellRule = { spells: Array<bigint> };

export type LcuMapTutorialCard = {
  description: string;
  footer: string;
  header: string;
  imagePath: string;
};
