// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MatchDetail = {
  gameId: bigint;
  gameDuration: bigint;
  gameMode: string;
  gameCreation: bigint;
  queueId: bigint;
  participants: Array<Participant>;
};

export type MatchSummary = {
  gameId: bigint;
  championId: bigint;
  win: boolean;
  kills: bigint;
  deaths: bigint;
  assists: bigint;
  cs: bigint;
  gameDuration: bigint;
  gameMode: string;
  gameCreation: bigint;
  queueId: bigint;
};

export type Participant = {
  puuid: string;
  championId: bigint;
  summonerName: string;
  teamId: bigint;
  kills: bigint;
  deaths: bigint;
  assists: bigint;
  totalDamageDealtToChampions: bigint;
  totalDamageTaken: bigint;
  goldEarned: bigint;
  visionScore: bigint;
  cs: bigint;
  items: [bigint, bigint, bigint, bigint, bigint, bigint, bigint];
  spell1Id: bigint;
  spell2Id: bigint;
  perkPrimaryStyle: bigint;
  perkSubStyle: bigint;
  win: boolean;
};
