// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CherryAugment = {
  id: bigint;
  nameTra: string;
  augmentSmallIconPath: string;
  rarity: string;
};

export type MatchDetail = {
  gameId: bigint;
  gameDuration: bigint;
  gameMode: string;
  gameCreation: bigint;
  queueId: bigint;
  participants: Array<Participant>;
};

export type MatchOutcome = "victory" | "defeat" | "remake" | "terminated";

export type MatchSummary = {
  gameId: bigint;
  championId: bigint;
  win: boolean;
  outcome: MatchOutcome;
  teamId: bigint;
  kills: bigint;
  deaths: bigint;
  assists: bigint;
  cs: bigint;
  totalDamageDealtToChampions: bigint;
  damageShare: number;
  spell1Id: bigint;
  spell2Id: bigint;
  perkPrimaryRuneId: bigint;
  perkSubStyleId: bigint;
  playerAugments: [bigint, bigint, bigint, bigint, bigint, bigint];
  items: [bigint, bigint, bigint, bigint, bigint, bigint, bigint];
  mapId: bigint;
  gameDuration: bigint;
  gameMode: string;
  gameMutator: string;
  gameCreation: bigint;
  queueId: bigint;
  participants: Array<MatchSummaryParticipant>;
};

export type MatchSummaryParticipant = {
  puuid: string;
  championId: bigint;
  gameName: string;
  tagLine: string;
  teamId: bigint;
};

export type Participant = {
  puuid: string;
  championId: bigint;
  summonerName: string;
  gameName: string;
  tagLine: string;
  teamId: bigint;
  kills: bigint;
  deaths: bigint;
  assists: bigint;
  totalDamageDealtToChampions: bigint;
  totalDamageTaken: bigint;
  goldEarned: bigint;
  visionScore: bigint;
  cs: bigint;
  items: [bigint, bigint, bigint, bigint, bigint, bigint, bigint];
  spell1Id: bigint;
  spell2Id: bigint;
  perkPrimaryStyle: bigint;
  perkSubStyle: bigint;
  win: boolean;
};
