// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {
  ChampSelectSessionData,
  GameflowSessionData,
  MatchmakingReadyCheckData,
  MatchmakingSearchData,
  TeamMember,
} from "./lcu_events";
import type { RawMatchSummaryGame } from "./matches";
import type { SummonerInfo } from "./summoner";

export type OngoingGameMatchHistoriesUpdated = {
  phase: OngoingGamePhase;
  state: OngoingGameMatchHistoryState;
};

export type OngoingGameMatchHistoryState = {
  game_id: bigint | null;
  puuid: string;
  team_id: bigint;
  status: OngoingGamePlayerLoadStatus;
  games: Array<RawMatchSummaryGame> | null;
};

export type OngoingGamePhase =
  | "Idle"
  | "Matchmaking"
  | "ReadyCheck"
  | "ChampSelect"
  | "InGame";

export type OngoingGamePlayerLoadStatus =
  | "idle"
  | "loading"
  | "ready"
  | "failed";

export type OngoingGameSummonerState = {
  game_id: bigint | null;
  puuid: string;
  team_id: bigint;
  status: OngoingGamePlayerLoadStatus;
  summoner: SummonerInfo | null;
};

export type OngoingGameSummonersUpdated = {
  phase: OngoingGamePhase;
  state: OngoingGameSummonerState;
};

export type OngoingGameUpdated = {
  phase: OngoingGamePhase;
  lifecycle_game_id: bigint | null;
  /**
   * User-selected match-history mode tag.
   * - "__current_mode__": follow current queue mode
   * - `q_xxx`: fixed queue mode
   * - None: all modes
   */
  match_history_tag: string | null;
  /**
   * Queue id resolved from the current game context.
   */
  effective_queue_id: bigint | null;
  /**
   * Effective SGP mode tag after resolving `match_history_tag` against current context.
   */
  effective_mode_tag: string | null;
  match_histories_pending: boolean;
  summoner_states: Array<OngoingGameSummonerState>;
  history_states: Array<OngoingGameMatchHistoryState>;
  gameflow_session: GameflowSessionData | null;
  matchmaking_search: MatchmakingSearchData | null;
  ready_check: MatchmakingReadyCheckData | null;
  champ_select_session: ChampSelectSessionData | null;
  team_members: Array<TeamMember>;
};
