// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LcuQueue = {
  id: bigint;
  name: string;
  shortName: string;
  description: string;
  detailedDescription: string;
  gameSelectModeGroup: string;
  gameSelectCategory: string;
  gameSelectPriority: bigint;
};
