// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SummonerInfo = {
  puuid: string;
  gameName: string;
  tagLine: string;
  profileIconId: bigint;
  summonerLevel: bigint;
  level: bigint;
  privacy: string;
  accountId: bigint;
  id: bigint;
  name: string;
  internalName: string;
  expPoints: bigint;
  expToNextLevel: bigint;
  levelAndXpVersion: bigint;
  lastGameDate: bigint;
  revisionDate: bigint;
  revisionId: bigint;
  nameChangeFlag: boolean;
  unnamed: boolean;
};

export type SummonerSearchResult = {
  puuid: string;
  gameName: string;
  tagLine: string;
  profileIconId: bigint;
  summonerLevel: bigint;
  sgpServerId: string;
  privacy: string;
};
