// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdaterSourceDto = "auto" | "gitee" | "github";

export type UpdaterStateDto = {
  kind: UpdaterStatusKindDto;
  currentVersion: string;
  latestVersion: string | null;
  notes: string | null;
  source: UpdaterSourceDto | null;
  message: string | null;
};

export type UpdaterStatusKindDto =
  | "idle"
  | "checking"
  | "upToDate"
  | "updateAvailable"
  | "installing"
  | "error";
