/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedPlayersRouteImport } from './routes/saved-players'
import { Route as OngoingGameRouteImport } from './routes/ongoing-game'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GameRouteImport } from './routes/game'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as AutoSelectRouteImport } from './routes/auto-select'
import { Route as AutoReplyRouteImport } from './routes/auto-reply'
import { Route as AutoGameflowRouteImport } from './routes/auto-gameflow'
import { Route as IndexRouteImport } from './routes/index'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedPlayersRoute = SavedPlayersRouteImport.update({
  id: '/saved-players',
  path: '/saved-players',
  getParentRoute: () => rootRouteImport,
} as any)
const OngoingGameRoute = OngoingGameRouteImport.update({
  id: '/ongoing-game',
  path: '/ongoing-game',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoSelectRoute = AutoSelectRouteImport.update({
  id: '/auto-select',
  path: '/auto-select',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoReplyRoute = AutoReplyRouteImport.update({
  id: '/auto-reply',
  path: '/auto-reply',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoGameflowRoute = AutoGameflowRouteImport.update({
  id: '/auto-gameflow',
  path: '/auto-gameflow',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auto-gameflow': typeof AutoGameflowRoute
  '/auto-reply': typeof AutoReplyRoute
  '/auto-select': typeof AutoSelectRoute
  '/automation': typeof AutomationRoute
  '/game': typeof GameRoute
  '/history': typeof HistoryRoute
  '/ongoing-game': typeof OngoingGameRoute
  '/saved-players': typeof SavedPlayersRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auto-gameflow': typeof AutoGameflowRoute
  '/auto-reply': typeof AutoReplyRoute
  '/auto-select': typeof AutoSelectRoute
  '/automation': typeof AutomationRoute
  '/game': typeof GameRoute
  '/history': typeof HistoryRoute
  '/ongoing-game': typeof OngoingGameRoute
  '/saved-players': typeof SavedPlayersRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auto-gameflow': typeof AutoGameflowRoute
  '/auto-reply': typeof AutoReplyRoute
  '/auto-select': typeof AutoSelectRoute
  '/automation': typeof AutomationRoute
  '/game': typeof GameRoute
  '/history': typeof HistoryRoute
  '/ongoing-game': typeof OngoingGameRoute
  '/saved-players': typeof SavedPlayersRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/tools': typeof ToolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auto-gameflow'
    | '/auto-reply'
    | '/auto-select'
    | '/automation'
    | '/game'
    | '/history'
    | '/ongoing-game'
    | '/saved-players'
    | '/settings'
    | '/statistics'
    | '/tools'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auto-gameflow'
    | '/auto-reply'
    | '/auto-select'
    | '/automation'
    | '/game'
    | '/history'
    | '/ongoing-game'
    | '/saved-players'
    | '/settings'
    | '/statistics'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/auto-gameflow'
    | '/auto-reply'
    | '/auto-select'
    | '/automation'
    | '/game'
    | '/history'
    | '/ongoing-game'
    | '/saved-players'
    | '/settings'
    | '/statistics'
    | '/tools'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutoGameflowRoute: typeof AutoGameflowRoute
  AutoReplyRoute: typeof AutoReplyRoute
  AutoSelectRoute: typeof AutoSelectRoute
  AutomationRoute: typeof AutomationRoute
  GameRoute: typeof GameRoute
  HistoryRoute: typeof HistoryRoute
  OngoingGameRoute: typeof OngoingGameRoute
  SavedPlayersRoute: typeof SavedPlayersRoute
  SettingsRoute: typeof SettingsRoute
  StatisticsRoute: typeof StatisticsRoute
  ToolsRoute: typeof ToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-players': {
      id: '/saved-players'
      path: '/saved-players'
      fullPath: '/saved-players'
      preLoaderRoute: typeof SavedPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ongoing-game': {
      id: '/ongoing-game'
      path: '/ongoing-game'
      fullPath: '/ongoing-game'
      preLoaderRoute: typeof OngoingGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-select': {
      id: '/auto-select'
      path: '/auto-select'
      fullPath: '/auto-select'
      preLoaderRoute: typeof AutoSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-reply': {
      id: '/auto-reply'
      path: '/auto-reply'
      fullPath: '/auto-reply'
      preLoaderRoute: typeof AutoReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-gameflow': {
      id: '/auto-gameflow'
      path: '/auto-gameflow'
      fullPath: '/auto-gameflow'
      preLoaderRoute: typeof AutoGameflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutoGameflowRoute: AutoGameflowRoute,
  AutoReplyRoute: AutoReplyRoute,
  AutoSelectRoute: AutoSelectRoute,
  AutomationRoute: AutomationRoute,
  GameRoute: GameRoute,
  HistoryRoute: HistoryRoute,
  OngoingGameRoute: OngoingGameRoute,
  SavedPlayersRoute: SavedPlayersRoute,
  SettingsRoute: SettingsRoute,
  StatisticsRoute: StatisticsRoute,
  ToolsRoute: ToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
